apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
    name: butterfly-theme
spec:
    displayName: Butterfly
    author:
        name: T-Rex
        website: 'https://playlab.eu.org'
    description: '一个Halo博客主题'
    logo: 'https://halo.run/logo'
    website: 'https://playlab.eu.org'
    repo: 'https://github.com/nasheep/butterfly-theme.git'
    settingName: theme-butterfly-setting
    configMapName: theme-butterfly-configMap
    version: 2.0.6
    require: 2.0.0
